version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./callboard.db
    volumes:
      - ./backend:/app
    command: poetry run fastapi dev app/main.py --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
